server/db/models/index.js, server/db/models/order.js
=> order model, associations

server/db/models/user.js
---
Added validations and default values
=> add user model

server/db/models/orderDetail.js
=> Chore: Created OrderDetail Model.

server/db/models/index.js
=> fixed associations

server/db/models/index.js
=> fixed associations again

server/db/models/payment.js
=> created payment model

server/db/models/payment.js
=> added the correct types

server/db/models/index.js
=> added syntax

server/db/models/index.js
=> fixed more associations

package-lock.json, server/api/index.js, server/api/products.js, server/index.js
=> created api/products route

client/components/AllProducts.js
=> Issue 15 all products

client/components/Orders/PurchasedOrders.js, client/components/user-home.js, client/routes.js, client/store/index.js, client/store/orders.js, server/index.js
=> Reducer for orders

client/components/AllProducts.js, client/components/navbar.js, client/routes.js, client/store/product.js
=> working all products, and past orders

client/components/Orders/PurchasedOrders.js
=> minor changes

client/components/SingleProduct.js, client/store/product.js
=> 'Chore: Created SingleProduct Comp., updated reducer for SingleProduct'.

client/components/AllProducts.js
=> all products comp. fixed

client/components/Account.js, client/components/PurchasedOrders.js, client/components/SingleProduct.js, client/components/user-home.js, public/index.html, public/toastr.css, server/api/users.js
=> lost some stuff in the last merge, added toastr again, code cleanup

client/routes.js, public/index.html
=> toastr working

client/components/SingleProduct.js, package-lock.json, package.json
=> feat: shoppingCart- just the singleProduct/localstorage stuff

client/components/SingleProduct.js
=> color dropdown functioning

client/components/SingleProduct.js
=> updated toastr message

client/components/user-home.spec.js, client/store/product.js, client/store/product.spec.js, client/store/user.spec.js, script/seed.js, server/api/orders.js, server/api/orders.spec.js, server/api/products.js, server/api/products.spec.js
=> tests: most api routes completed, attempts made pending

client/components/ProductForm.js
=> product form up to date

client/components/Account.js, client/components/ProductComponent.js, client/components/ProductForm.js, client/components/user-home.js
=> Working branch

client/components/ProductComponent.js
=> feat: fixed small error

client/components/auth-form.js, client/components/user-home.js, e2e/tests.js
=> new login tests

client/components/SingleProduct.js, client/routes.js
=> Cart testing
